codecov:
  require_ci_to_pass: true
  branch: main
  max_report_age: false

comment:
  layout: "diff,flags,tree"
  behavior: default
  require_changes: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false

ignore:
  - "^/tests/**/*" # ignore test harness code

flag_management:
  individual_flags:
    - name: smart-tests
      carryforward: true
      carryforward_mode: "labels"
      statuses:
        - type: "project"
        - type: "patch"
