name: Workflow for Codecov example-python
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r requirements/dev.txt
      - name: Run tests and collect coverage
        run: pytest --cov=api tests/
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          name: codecov-run
          url: https://codecov-dev.apps.gold.devops.gov.bc.ca
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          flags: smart-tests
